// Generated by build.js — offline support
const CACHE = "isc-90c30ee8fd";
const FILES = ["./","index.html","syllabus.html","exam.html","progress.html","glossary.html","timeline.html","search.html","404.html","topic-01.html","topic-02.html","topic-03.html","topic-04.html","topic-05.html","topic-06.html","topic-07.html","topic-08.html","topic-09.html","topic-10.html","topic-11.html","topic-12.html","topic-13.html","topic-14.html","topic-15.html","data/meta.js","data/mcq.js","data/search.js","assets/css/style.css","assets/js/app.js","favicon.svg","manifest.webmanifest","fonts/NafeesNastaleeq.woff2","fonts/Amiri-Regular.woff2","fonts/Amiri-Bold.woff2","icons/icon-192.png","icons/icon-512.png"];
self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((r) => r || fetch(e.request).then((res) => { const cp = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, cp)); return res; }).catch(() => caches.match("404.html"))));
});
