// Generated by build.js — offline support
const CACHE = "isc-aaa51765ba";
const ASSETS = ["data/meta.js?v=b21d7416","data/mcq.js?v=b21d7416","data/search.js?v=b21d7416","assets/css/style.css?v=b21d7416","assets/js/app.js?v=b21d7416","favicon.svg","manifest.webmanifest","fonts/NafeesNastaleeq.woff2","fonts/Amiri-Regular.woff2","fonts/Amiri-Bold.woff2","icons/icon-192.png","icons/icon-512.png"];
self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => Promise.all(ASSETS.map((u) => fetch(u, { cache: "reload" }).then((r) => r.ok && !r.redirected ? c.put(u, r) : null).catch(() => null)))).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
// store a clean (non-redirected) copy of a response
function clean(res) { return res.blob().then((b) => new Response(b, { status: res.status, statusText: res.statusText, headers: res.headers })); }
function pageKeys(url) { const u = new URL(url); u.search = ""; u.hash = ""; const p = u.pathname; const alts = [u.href]; if (p.endsWith(".html")) alts.push(u.origin + p.slice(0, -5)); else if (p.endsWith("/")) alts.push(u.origin + p + "index.html"); else alts.push(u.origin + p + ".html"); return alts; }
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;
  if (req.mode === "navigate" || (req.headers.get("accept") || "").includes("text/html")) {
    // network first: return the live response untouched (redirects work normally); keep a clean copy for offline use
    e.respondWith(fetch(req).then((res) => {
      if (res.ok && res.type === "basic") { const cp = res.clone(); clean(cp).then((r) => caches.open(CACHE).then((c) => c.put(new URL(cp.url || req.url).href.split("#")[0], r))).catch(() => {}); }
      return res;
    }).catch(() => caches.open(CACHE).then(async (c) => { for (const k of pageKeys(req.url)) { const r = await c.match(k); if (r) return r; } return (await c.match(new URL("./", location).href)) || Response.error(); })));
    return;
  }
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok && !res.redirected && res.type === "basic") { const cp = res.clone(); caches.open(CACHE).then((c) => c.put(req, cp)); }
    return res;
  })));
});
